name: Frontend - Deploy Static Website

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Frontend to Azure Storage
        run: |
          az storage blob upload-batch \
            --account-name preciouswebsite \
            -s frontend \
            -d '$web' \
            --auth-mode key
